### ISSUE TITLE
Unable to provision SD card

### ISSUE THREAD

**Issue by coughlanio** [MiSTer-devel/SD-Installer-Win64_MiSTer#1]
When trying to run the SD Card Installer (both v1.0.0.1 and v2.0.0.0) I run into an error:

![capture](https://user-images.githubusercontent.com/16995769/35192392-b3b0cca8-fed4-11e7-8935-c97316534b34.PNG)

This is using the default Team 8GB Micro SD card included with the DE10-Nano, connected via a Kingston MobileLite G4 USB SD Card reader, on a relatively clean install of Windows 10 Pro (Build 16299.192)

**Comment by coughlanio** [comment]
I don't have any other SD Card Readers or Windows installations to try on, but I did try with a USB flash drive, and encountered the same problem.

**Comment by sorgelig** [comment]
I found that i need to click Full Install 2 times. First time usually gives error while second time works. Ignore  format offering from windows.
In options menu choose to open the logger. Then make a Full Install again - see if there messages giving a clue why it doesn't work.

**Comment by sorgelig** [comment]
Note: you cannot change installer executable as v2 requires other file layout. You only can use full release archive where older installer included.

**Comment by coughlanio** [comment]
Thanks for the feedback, I didn't switch any executables, I tried using the full installer package for both v1 and v2. I didn't notice that the `Options` menu was actually a menu, Windows GUI makes it look like a label :smile: 

I will try again when I'm at my primary PC. Thanks!
