### ISSUE TITLE
Default block size set to 128K, could it be set smaller?

### ISSUE THREAD

**Issue by MAME-GETTER** [MiSTer-devel/SD-Installer-Win64_MiSTer#10]
Looks like the default block size for the SD-Installer is set to 128K. 

The down side to this is that all files smaller than 128K end up taking up a minimum of 128K. 
Many symlinks are under 50b but with the default block size set to 128K they take more space than they have to on the SD card especially when there are a lot of them.

**Comment by sorgelig** [comment]
Actually you can simply re-format exFAT partition with any cluster size. Just don't go too low. I suggest not to go lower than 32KB.

**Comment by MAME-GETTER** [comment]
Can the SD installer set block size similar to how dd for Linux does when writing an image?

On dd it would be something this:

`dd bs=4M if=rando.img of=/dev/sdX conv=fsync`

**Comment by dukrous** [comment]
I submitted a pull request to fix the blocksize to 32K. https://github.com/MiSTer-devel/SD-InstallTool_Win_MiSTer/pull/3

**Comment by MAME-GETTER** [comment]
Closed
