### ISSUE TITLE
Problem release_20241007.7z

### ISSUE THREAD

**Issue by jfml2020** [MiSTer-devel/SD-Installer-Win64_MiSTer#19]
![20241007_185253](https://github.com/user-attachments/assets/51c58e1a-4959-45fe-9597-fbda9ca11769)

The update is stuck without finishing the update.I tried manual form and it's still the same 
. Versión release_20241007.7z

**Comment by jfml2020** [comment]
![20241007_185253](https://github.com/user-attachments/assets/f53ba50f-7773-40ba-989e-3063119c7759)

**Comment by jfml2020** [comment]
> The update is stuck without finishing the update.I tried manual form and it's still the same . Versión release_20241007.7z

![Uploading 20241007_185253.jpg…]()

**Comment by jfml2020** [comment]
![Uploading 20241007_185253.jpg…]()

**Comment by jfml2020** [comment]
![Uploading 20241007_185253.jpg…]()

**Comment by jfml2020** [comment]
Manually from Windows application mister sd card utility release_20241008 clean full.
I'm reinstalling everything from scratch and then I'll put the backup of ROMs etc
No problem with update_all....

**Comment by sorgelig** [comment]
try new release

**Comment by jfml2020** [comment]
> try new release

Indeed version 20241008 works fine. Thanks
