### ISSUE TITLE
Add application opkg to buildroot 

### ISSUE THREAD

**Issue by amoore2600** [MiSTer-devel/SD-Installer-Win64_MiSTer#6]
This is a feature request more so then a bug. Please close/remove if you feel this does not belong here.

Please add the opkg package manager application during the creation of the buildroot process. I believe opkg is included in buildroot. I feel that this could become a much better replacement for the update scripts. opkg would allow for better management of installing cores, paltes, scripts and updates. It would also allow for official and unofficial repos. opkg would also allow for better security as packages/repos could be pgp signe and would stream line the update process as every package does not need to checked. 

At this point I am not asking for official repos just that the opkg be included so we could make our own repos now.

**Comment by sorgelig** [comment]
I don't like idea of making constructor from Linux. 
It's not the way MiSTer is going to.
