### ISSUE TITLE
Cleaning, wiping, and creating partitions highly inconsistent/broken

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/SD-Installer-Win64_MiSTer#9]
I ran the sd installer as shown in the guides. I first got many errors acting as if it can't create partitions. Tried wipe, doesn't work. Opened a cmd prompt as admin, run diskpart, force cleaned the partitions on the sd card. This might be due to having an extremely large micro sd card I'm using (Samsung 256gb EVO Plus SDXC).

Spamming it and trying it over and over, kinda randomly finagling around after cleaning the partition manually in diskpart, it still didn't work, then finally worked. Here's the logs.

```
`CheckUpdatePackage()...
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done
Unable to lock volume \\?\Volume{85f43e78-47b6-11ea-bcaa-d8cb8a1853ee}
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
ErrorCode: 0x80004005, Message: 'Access is denied'
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
ErrorCode: 0x80004005, Message: 'Access is denied'
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done
ErrorCode: 0x80004005, Message: 'Access is denied'
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
ErrorCode: 0x80004005, Message: 'Access is denied'
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
ErrorCode: 0x80004005, Message: 'Access is denied'
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done
ErrorCode: 0x80004005, Message: 'Access is denied'
ErrorCode: 0x80004005, Message: 'The parameter is incorrect'
Starting to copy files\linux\uboot.img image to partition with offset 500165662
File size: 518167
Aligned size: 518656
1 iterations will be done with buffer size 1048576

1 / 1 (buffered ops) - 518167 / 518656
OK

Format finished successfully
Unable to copy file mt32-rom-data\README
Unable to copy file soundfonts\README
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE2
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done`
```

**Comment by sorgelig** [comment]
By coincidence i had a new 256GB SD card i've bought for MiSTer but didn't format yet.
So i've just formatted it without issues from the first time.
Operation of splitting and formatting the storage is not trivial and in most cases tricky. It may also depend on apps installed on Windows such as antiviruses or other guards.
Windows 10 Pro 64bit with latest update.

**Comment by sofakng** [comment]
I had similar issues with my 512GB SD card.

`ErrorCode: 0x80004005, Message: 'Access is denied'
ErrorCode: 0x80004005, Message: 'The parameter is incorrect'
Starting to copy files\linux\uboot.img image to partition with offset 1000140592
File size: 518167
Aligned size: 518656
1 iterations will be done with buffer size 1048576

1 / 1 (buffered ops) - 518167 / 518656
OK

Format finished successfully
Unable to copy file mt32-rom-data\README
Unable to copy file soundfonts\README
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE5
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE5
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done
`

However it says it succeeded afterwards?

**Comment by sorgelig** [comment]
why it shouldn't be normal? System always reserve some space at beginning. 1MB from 512GB doesn't look too much to worry about and do manual re-partition.

**Comment by aberusugi** [comment]
I just got one of these in fresh.

https://www.amazon.com/gp/product/B0758NHWS8/

![image](https://user-images.githubusercontent.com/16388068/85058558-846d8180-b15f-11ea-865a-1b348a0f20cf.png)

![image](https://user-images.githubusercontent.com/16388068/85058599-92230700-b15f-11ea-9530-37fea55a77db.png)

Run it a second time and it works. This is what I have had to do to get the utility to install MiSTer on any MicroSD I have used so far. Here's the log this time, forgot to open it when I got the error at first in the screenshot above, but...

```
Unable to lock volume \\?\Volume{85f43e78-47b6-11ea-bcaa-d8cb8a1853ee}
ErrorCode: 0x80004005, Message: 'The parameter is incorrect'
Starting to copy files\linux\uboot.img image to partition with offset 499731907
File size: 518167
Aligned size: 518656
1 iterations will be done with buffer size 1048576

1 / 1 (buffered ops) - 518167 / 518656
OK

Format finished successfully
Unable to copy file mt32-rom-data\README
Unable to copy file soundfonts\README
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE4
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE4
Read successful 512 bytes
Card has new MiSTer layout. Partial update can be applied
done

```

I guess it works if you just keep pushing the button when it fails, but the initial full install on a fresh drive bought from SanDisk fails. I wonder if the default file system of these raw drives is causing the problem... Or if Windows 10 1909/2004 (both versions I've used now) are causing the problem for some reason...

Either way, I guess if it works it works, just trying to help!

**Comment by birdybro** [comment]
Forgot I didn't close this.
